fixed buggy exec -> flock modifying the file time. we now check to get a lock then check the file time, hopefully properly

diff --git a/utils/pulseox-launcher b/utils/pulseox-launcher
--- a/utils/pulseox-launcher
+++ b/utils/pulseox-launcher
@@ -25,16 +25,21 @@ play_warning () {
 }
 
 # Try to acquire a lock, exit if cannot
-exec 200>$we_ran_tracker_file
+exec 200<$we_ran_tracker_file
 if ! flock --verbose -n 200; then
 	# Warning sound for those who hold buttons down
+	echo "Couldn't obtain lock: $we_ran_tracker_file" >&2
 	play_warning
     exit 1
 fi
-if filetime_within_ms "$we_ran_tracker_file" 3000; then
+if [[ ! -f $we_ran_tracker_file ]]; then
+	echo "Lockfile doesn't exist. Assuming all is well." >&2
+elif filetime_within_ms "$we_ran_tracker_file" 3000; then
+	echo "Lock is too young: $we_ran_tracker_file" >&2
 	play_warning
 	exit 1
 fi
+touch "$we_ran_tracker_file"
 # Play soothing reward to those who don't know how to tap a kb button
 play -qn synth -j 3 sin %3 sin %-2 sin %-5 sin %-9 sin %-14 sin %-21 fade h .01 2 1.5 delay 1.3 .5 .76 .54 .27 remix - fade h 0 2.3 .5 norm -1
 
